### PR TITLE
fix: 🐛allow all clippy lints on the generated tetragon.rs

### LINKED ISSUE #4: Add `#[allow(clippy::all)]` to the generated module
Else it is not playing well with the clippy in main project. I can't figure out a way to ignore `target/build` path when running clippy.

### PR DESCRIPTION
**Pull request by Aditeya**
closes #4

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1,6 +1,6 @@
 mod tetragon {
     // NOTE: Since this is generated by tonic theres nothing else we can do.
-    #![allow(clippy::large_enum_variant)]
+    #![allow(clippy::all)]
```
Comment (dilawar) [inline src/lib.rs:3]: I still don't see this at the top of generated module @Aditeya

Comment (Aditeya) [reply src/lib.rs:3]: I don't understand, do you mean the `tetragon.rs` file that's generated or the lib.rs file?

Comment (Aditeya) [reply src/lib.rs:3]: https://github.com/tokio-rs/prost/issues/661#issuecomment-1156606409

Comment (dilawar) [reply src/lib.rs:3]: Hmm .. I guess clippy cli options are overwriting it. Even when i add `#[clippy(allow::all)]`, clippy still fails because of `-Dmissing_docs` passed to thr cli.

Comment (Aditeya) [reply src/lib.rs:3]: apprently `missing_docs` isn't under `clippy::*`. I pushed a fix.
